//------------------------------------------------------------------------------
// <auto-generated>
//    姝や唬鐮佹槸鏍规嵁妯℃澘鐢熸垚鐨勩€?//
//    鎵嬪姩鏇存敼姝ゆ枃浠跺彲鑳戒細瀵艰嚧搴旂敤绋嬪簭涓彂鐢熷紓甯歌涓恒€?//    濡傛灉閲嶆柊鐢熸垚浠ｇ爜锛屽垯灏嗚鐩栧姝ゆ枃浠剁殑鎵嬪姩鏇存敼銆?// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppInfo
    {
        public AppInfo()
        {
            this.EmailMessages = new HashSet<EmailMessage>();
            this.Feedbacks = new HashSet<Feedback>();
            this.FriendLinks = new HashSet<FriendLink>();
            this.News = new HashSet<News>();
            this.NewsCategories = new HashSet<NewsCategory>();
            this.ServiceInfoes = new HashSet<ServiceInfo>();
            this.SiteADs = new HashSet<SiteAD>();
            this.SMSMessages = new HashSet<SMSMessage>();
            this.UserInfoes = new HashSet<UserInfo>();
            this.EmailConfigs = new HashSet<EmailConfig>();
            this.SMSConfigs = new HashSet<SMSConfig>();
        }
    
        public System.Guid AppID { get; set; }
        public string AppName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<EmailMessage> EmailMessages { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<FriendLink> FriendLinks { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<NewsCategory> NewsCategories { get; set; }
        public virtual ICollection<ServiceInfo> ServiceInfoes { get; set; }
        public virtual ICollection<SiteAD> SiteADs { get; set; }
        public virtual ICollection<SMSMessage> SMSMessages { get; set; }
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
        public virtual ICollection<EmailConfig> EmailConfigs { get; set; }
        public virtual ICollection<SMSConfig> SMSConfigs { get; set; }
    }
}
