//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppInfo
    {
        public AppInfo()
        {
            this.EmailMessages = new HashSet<EmailMessage>();
            this.Feedbacks = new HashSet<Feedback>();
            this.FriendLinks = new HashSet<FriendLink>();
            this.News = new HashSet<News>();
            this.NewsCategories = new HashSet<NewsCategory>();
            this.ServiceInfoes = new HashSet<ServiceInfo>();
            this.SiteADs = new HashSet<SiteAD>();
            this.SMSMessages = new HashSet<SMSMessage>();
            this.UserInfoes = new HashSet<UserInfo>();
            this.EmailConfigs = new HashSet<EmailConfig>();
            this.SMSConfigs = new HashSet<SMSConfig>();
        }
    
        public System.Guid AppID { get; set; }
        public string AppName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<EmailMessage> EmailMessages { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<FriendLink> FriendLinks { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<NewsCategory> NewsCategories { get; set; }
        public virtual ICollection<ServiceInfo> ServiceInfoes { get; set; }
        public virtual ICollection<SiteAD> SiteADs { get; set; }
        public virtual ICollection<SMSMessage> SMSMessages { get; set; }
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
        public virtual ICollection<EmailConfig> EmailConfigs { get; set; }
        public virtual ICollection<SMSConfig> SMSConfigs { get; set; }
    }
}
