//------------------------------------------------------------------------------
// <auto-generated>
//    姝や唬鐮佹槸鏍规嵁妯℃澘鐢熸垚鐨勩€?//
//    鎵嬪姩鏇存敼姝ゆ枃浠跺彲鑳戒細瀵艰嚧搴旂敤绋嬪簭涓彂鐢熷紓甯歌涓恒€?//    濡傛灉閲嶆柊鐢熸垚浠ｇ爜锛屽垯灏嗚鐩栧姝ゆ枃浠剁殑鎵嬪姩鏇存敼銆?// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentInfo
    {
        public ComponentInfo()
        {
            this.ControlInfoes = new HashSet<ControlInfo>();
            this.SearchKeywords = new HashSet<SearchKeyword>();
        }
    
        public System.Guid RowID { get; set; }
        public System.Guid ServiceID { get; set; }
        public string Name { get; set; }
        public string spName { get; set; }
        public string Description { get; set; }
        public int Sort { get; set; }
        public int Status { get; set; }
    
        public virtual ServiceInfo ServiceInfo { get; set; }
        public virtual ICollection<ControlInfo> ControlInfoes { get; set; }
        public virtual ICollection<SearchKeyword> SearchKeywords { get; set; }
    }
}
