//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentInfo
    {
        public ComponentInfo()
        {
            this.ControlInfoes = new HashSet<ControlInfo>();
            this.SearchKeywords = new HashSet<SearchKeyword>();
        }
    
        public System.Guid RowID { get; set; }
        public System.Guid ServiceID { get; set; }
        public string Name { get; set; }
        public string spName { get; set; }
        public string Description { get; set; }
        public int Sort { get; set; }
        public int Status { get; set; }
    
        public virtual ServiceInfo ServiceInfo { get; set; }
        public virtual ICollection<ControlInfo> ControlInfoes { get; set; }
        public virtual ICollection<SearchKeyword> SearchKeywords { get; set; }
    }
}
