//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileStorage
    {
        public string FileKey { get; set; }
        public string FileName { get; set; }
        public string VirtualPath { get; set; }
        public string PhysicalPath { get; set; }
        public string ServerAuthority { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
