//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendLink
    {
        public System.Guid RowID { get; set; }
        public System.Guid AppID { get; set; }
        public string SiteName { get; set; }
        public string SiteUrl { get; set; }
        public string LinkText { get; set; }
        public string LinkFileKey { get; set; }
        public int Sort { get; set; }
        public int RenderKind { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Status { get; set; }
    
        public virtual AppInfo AppInfo { get; set; }
    }
}
