//------------------------------------------------------------------------------
// <auto-generated>
//    姝や唬鐮佹槸鏍规嵁妯℃澘鐢熸垚鐨勩€?//
//    鎵嬪姩鏇存敼姝ゆ枃浠跺彲鑳戒細瀵艰嚧搴旂敤绋嬪簭涓彂鐢熷紓甯歌涓恒€?//    濡傛灉閲嶆柊鐢熸垚浠ｇ爜锛屽垯灏嗚鐩栧姝ゆ枃浠剁殑鎵嬪姩鏇存敼銆?// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendLink
    {
        public System.Guid RowID { get; set; }
        public System.Guid AppID { get; set; }
        public string SiteName { get; set; }
        public string SiteUrl { get; set; }
        public string LinkText { get; set; }
        public string LinkFileKey { get; set; }
        public int Sort { get; set; }
        public int RenderKind { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Status { get; set; }
    
        public virtual AppInfo AppInfo { get; set; }
    }
}
