//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int RowID { get; set; }
        public System.Guid AppID { get; set; }
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Origin { get; set; }
        public string Author { get; set; }
        public string ImageFileKey { get; set; }
        public string AttachmentFileKey { get; set; }
        public string Tag { get; set; }
        public int ViewCount { get; set; }
        public int Flags { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AppInfo AppInfo { get; set; }
        public virtual NewsCategory NewsCategory { get; set; }
    }
}
