//------------------------------------------------------------------------------
// <auto-generated>
//    姝や唬鐮佹槸鏍规嵁妯℃澘鐢熸垚鐨勩€?//
//    鎵嬪姩鏇存敼姝ゆ枃浠跺彲鑳戒細瀵艰嚧搴旂敤绋嬪簭涓彂鐢熷紓甯歌涓恒€?//    濡傛灉閲嶆柊鐢熸垚浠ｇ爜锛屽垯灏嗚鐩栧姝ゆ枃浠剁殑鎵嬪姩鏇存敼銆?// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int RowID { get; set; }
        public System.Guid AppID { get; set; }
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Origin { get; set; }
        public string Author { get; set; }
        public string ImageFileKey { get; set; }
        public string AttachmentFileKey { get; set; }
        public string Tag { get; set; }
        public int ViewCount { get; set; }
        public int Flags { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AppInfo AppInfo { get; set; }
        public virtual NewsCategory NewsCategory { get; set; }
    }
}
