//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsCategory
    {
        public NewsCategory()
        {
            this.News = new HashSet<News>();
        }
    
        public int RowID { get; set; }
        public System.Guid AppID { get; set; }
        public int ParentID { get; set; }
        public string Name { get; set; }
        public int Sort { get; set; }
        public int Level { get; set; }
        public string Path { get; set; }
        public string SEO_Keyword { get; set; }
        public string SEO_Description { get; set; }
    
        public virtual AppInfo AppInfo { get; set; }
        public virtual ICollection<News> News { get; set; }
    }
}
