//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleInfo
    {
        public RoleInfo()
        {
            this.RoleControlMaps = new HashSet<RoleControlMap>();
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public System.Guid RowID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<RoleControlMap> RoleControlMaps { get; set; }
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
