//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchKeyword
    {
        public System.Guid ComponentID { get; set; }
        public string Keyword { get; set; }
        public string Pinyin { get; set; }
        public string PinyinCaps { get; set; }
        public int Count { get; set; }
        public int RecordCount { get; set; }
    
        public virtual ComponentInfo ComponentInfo { get; set; }
    }
}
