//------------------------------------------------------------------------------
// <auto-generated>
//    姝や唬鐮佹槸鏍规嵁妯℃澘鐢熸垚鐨勩€?//
//    鎵嬪姩鏇存敼姝ゆ枃浠跺彲鑳戒細瀵艰嚧搴旂敤绋嬪簭涓彂鐢熷紓甯歌涓恒€?//    濡傛灉閲嶆柊鐢熸垚浠ｇ爜锛屽垯灏嗚鐩栧姝ゆ枃浠剁殑鎵嬪姩鏇存敼銆?// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.UserControlMaps = new HashSet<UserControlMap>();
            this.RoleInfoes = new HashSet<RoleInfo>();
        }
    
        public System.Guid RowID { get; set; }
        public System.Guid AppID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Remark { get; set; }
        public System.DateTime LastSignInDate { get; set; }
        public string LastSignInIP { get; set; }
        public int Status { get; set; }
    
        public virtual AppInfo AppInfo { get; set; }
        public virtual ICollection<UserControlMap> UserControlMaps { get; set; }
        public virtual ICollection<RoleInfo> RoleInfoes { get; set; }
    }
}
