//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.UserControlMaps = new HashSet<UserControlMap>();
            this.RoleInfoes = new HashSet<RoleInfo>();
        }
    
        public System.Guid RowID { get; set; }
        public System.Guid AppID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Remark { get; set; }
        public System.DateTime LastSignInDate { get; set; }
        public string LastSignInIP { get; set; }
        public int Status { get; set; }
    
        public virtual AppInfo AppInfo { get; set; }
        public virtual ICollection<UserControlMap> UserControlMaps { get; set; }
        public virtual ICollection<RoleInfo> RoleInfoes { get; set; }
    }
}
