//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InfrastructureService_UserEntities : DbContext
    {
        public InfrastructureService_UserEntities()
            : base("name=InfrastructureService_UserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<EmailAuth> EmailAuths { get; set; }
        public DbSet<MobileAuth> MobileAuths { get; set; }
        public DbSet<OpenOAuth> OpenOAuths { get; set; }
        public DbSet<PersistentSession> PersistentSessions { get; set; }
        public DbSet<SignInLog> SignInLogs { get; set; }
    }
}
