//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Repository.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserControlMap
    {
        public System.Guid UserID { get; set; }
        public System.Guid ControlID { get; set; }
        public int PermissionFlags { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ControlInfo ControlInfo { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
