//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.Client.StorageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StorageConfig", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.Basic")]
    [System.SerializableAttribute()]
    public partial class StorageConfig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Net.IPEndPoint ListenedAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StorageUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Net.IPEndPoint ListenedAddress {
            get {
                return this.ListenedAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ListenedAddressField, value) != true)) {
                    this.ListenedAddressField = value;
                    this.RaisePropertyChanged("ListenedAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StorageUrl {
            get {
                return this.StorageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.StorageUrlField, value) != true)) {
                    this.StorageUrlField = value;
                    this.RaisePropertyChanged("StorageUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeaderEntity", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.Client.StorageService.QueryFileParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.Client.StorageService.GetFileUrlParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.Client.StorageService.SaveFileParameter))]
    public partial class HeaderEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AppIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AppID {
            get {
                return this.AppIDField;
            }
            set {
                if ((this.AppIDField.Equals(value) != true)) {
                    this.AppIDField = value;
                    this.RaisePropertyChanged("AppID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryFileParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.Basic")]
    [System.SerializableAttribute()]
    public partial class QueryFileParameter : InfrastructureService.Client.StorageService.HeaderEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileKey {
            get {
                return this.FileKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.FileKeyField, value) != true)) {
                    this.FileKeyField = value;
                    this.RaisePropertyChanged("FileKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFileUrlParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.Basic")]
    [System.SerializableAttribute()]
    public partial class GetFileUrlParameter : InfrastructureService.Client.StorageService.HeaderEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Drawing.Size> ImageThumbnailSizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileKey {
            get {
                return this.FileKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.FileKeyField, value) != true)) {
                    this.FileKeyField = value;
                    this.RaisePropertyChanged("FileKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Drawing.Size> ImageThumbnailSize {
            get {
                return this.ImageThumbnailSizeField;
            }
            set {
                if ((this.ImageThumbnailSizeField.Equals(value) != true)) {
                    this.ImageThumbnailSizeField = value;
                    this.RaisePropertyChanged("ImageThumbnailSize");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveFileParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.Basic")]
    [System.SerializableAttribute()]
    public partial class SaveFileParameter : InfrastructureService.Client.StorageService.HeaderEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileData {
            get {
                return this.FileDataField;
            }
            set {
                if ((object.ReferenceEquals(this.FileDataField, value) != true)) {
                    this.FileDataField = value;
                    this.RaisePropertyChanged("FileData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryFileResult", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.Basic")]
    [System.SerializableAttribute()]
    public partial class QueryFileResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileKey {
            get {
                return this.FileKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.FileKeyField, value) != true)) {
                    this.FileKeyField = value;
                    this.RaisePropertyChanged("FileKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StorageService.IStorageService")]
    public interface IStorageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/GetConfig", ReplyAction="http://tempuri.org/IStorageService/GetConfigResponse")]
        InfrastructureService.Client.StorageService.StorageConfig GetConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/SaveFile", ReplyAction="http://tempuri.org/IStorageService/SaveFileResponse")]
        void SaveFile(InfrastructureService.Client.StorageService.SaveFileParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/QueryFile", ReplyAction="http://tempuri.org/IStorageService/QueryFileResponse")]
        InfrastructureService.Client.StorageService.QueryFileResult QueryFile(InfrastructureService.Client.StorageService.QueryFileParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/GetFileUrl", ReplyAction="http://tempuri.org/IStorageService/GetFileUrlResponse")]
        string GetFileUrl(InfrastructureService.Client.StorageService.GetFileUrlParameter param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStorageServiceChannel : InfrastructureService.Client.StorageService.IStorageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StorageServiceClient : System.ServiceModel.ClientBase<InfrastructureService.Client.StorageService.IStorageService>, InfrastructureService.Client.StorageService.IStorageService {
        
        public StorageServiceClient() {
        }
        
        public StorageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InfrastructureService.Client.StorageService.StorageConfig GetConfig() {
            return base.Channel.GetConfig();
        }
        
        public void SaveFile(InfrastructureService.Client.StorageService.SaveFileParameter param) {
            base.Channel.SaveFile(param);
        }
        
        public InfrastructureService.Client.StorageService.QueryFileResult QueryFile(InfrastructureService.Client.StorageService.QueryFileParameter param) {
            return base.Channel.QueryFile(param);
        }
        
        public string GetFileUrl(InfrastructureService.Client.StorageService.GetFileUrlParameter param) {
            return base.Channel.GetFileUrl(param);
        }
    }
}
