//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfrastructureService.WebModel.SSOService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeaderEntity", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.SignUpParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.SignInParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.OAuthParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.SendAuthEmailParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.SendAuthMobileParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.SendFindPwdCodeParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.ChangePasswordParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.PagingParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.QueryUsersParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.QuerySignInLogsParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.IsUserNameExistsParameter))]
    public partial class HeaderEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AppIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AppID {
            get {
                return this.AppIDField;
            }
            set {
                if ((this.AppIDField.Equals(value) != true)) {
                    this.AppIDField = value;
                    this.RaisePropertyChanged("AppID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignUpParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class SignUpParameter : InfrastructureService.WebModel.SSOService.HeaderEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SmsCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SmsCode {
            get {
                return this.SmsCodeField;
            }
            set {
                if ((this.SmsCodeField.Equals(value) != true)) {
                    this.SmsCodeField = value;
                    this.RaisePropertyChanged("SmsCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignInParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.OAuthParameter))]
    public partial class SignInParameter : InfrastructureService.WebModel.SSOService.HeaderEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LogSignInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlatformField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientIP {
            get {
                return this.ClientIPField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIPField, value) != true)) {
                    this.ClientIPField = value;
                    this.RaisePropertyChanged("ClientIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LogSignIn {
            get {
                return this.LogSignInField;
            }
            set {
                if ((this.LogSignInField.Equals(value) != true)) {
                    this.LogSignInField = value;
                    this.RaisePropertyChanged("LogSignIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Platform {
            get {
                return this.PlatformField;
            }
            set {
                if ((object.ReferenceEquals(this.PlatformField, value) != true)) {
                    this.PlatformField = value;
                    this.RaisePropertyChanged("Platform");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OAuthParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class OAuthParameter : InfrastructureService.WebModel.SSOService.SignInParameter {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InfrastructureService.WebModel.SSOService.OAuthKind OAuthKindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InfrastructureService.WebModel.SSOService.OAuthKind OAuthKind {
            get {
                return this.OAuthKindField;
            }
            set {
                if ((this.OAuthKindField.Equals(value) != true)) {
                    this.OAuthKindField = value;
                    this.RaisePropertyChanged("OAuthKind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpenID {
            get {
                return this.OpenIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenIDField, value) != true)) {
                    this.OpenIDField = value;
                    this.RaisePropertyChanged("OpenID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendAuthEmailParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class SendAuthEmailParameter : InfrastructureService.WebModel.SSOService.HeaderEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InfrastructureService.WebModel.SSOService.AuthEmailKind KindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InfrastructureService.WebModel.SSOService.AuthEmailKind Kind {
            get {
                return this.KindField;
            }
            set {
                if ((this.KindField.Equals(value) != true)) {
                    this.KindField = value;
                    this.RaisePropertyChanged("Kind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendAuthMobileParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class SendAuthMobileParameter : InfrastructureService.WebModel.SSOService.HeaderEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InfrastructureService.WebModel.SSOService.AuthMobileKind KindField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InfrastructureService.WebModel.SSOService.AuthMobileKind Kind {
            get {
                return this.KindField;
            }
            set {
                if ((this.KindField.Equals(value) != true)) {
                    this.KindField = value;
                    this.RaisePropertyChanged("Kind");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendFindPwdCodeParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class SendFindPwdCodeParameter : InfrastructureService.WebModel.SSOService.HeaderEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailOrMobileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailOrMobile {
            get {
                return this.EmailOrMobileField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailOrMobileField, value) != true)) {
                    this.EmailOrMobileField = value;
                    this.RaisePropertyChanged("EmailOrMobile");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class ChangePasswordParameter : InfrastructureService.WebModel.SSOService.HeaderEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OldPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode {
            get {
                return this.AuthCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthCodeField, value) != true)) {
                    this.AuthCodeField = value;
                    this.RaisePropertyChanged("AuthCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword {
            get {
                return this.NewPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.NewPasswordField, value) != true)) {
                    this.NewPasswordField = value;
                    this.RaisePropertyChanged("NewPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OldPassword {
            get {
                return this.OldPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.OldPasswordField, value) != true)) {
                    this.OldPasswordField = value;
                    this.RaisePropertyChanged("OldPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.QueryUsersParameter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.QuerySignInLogsParameter))]
    public partial class PagingParameter : InfrastructureService.WebModel.SSOService.HeaderEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OnlyCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SkipStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OnlyCount {
            get {
                return this.OnlyCountField;
            }
            set {
                if ((this.OnlyCountField.Equals(value) != true)) {
                    this.OnlyCountField = value;
                    this.RaisePropertyChanged("OnlyCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SkipStatus {
            get {
                return this.SkipStatusField;
            }
            set {
                if ((this.SkipStatusField.Equals(value) != true)) {
                    this.SkipStatusField = value;
                    this.RaisePropertyChanged("SkipStatus");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryUsersParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class QueryUsersParameter : InfrastructureService.WebModel.SSOService.PagingParameter {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InfrastructureService.WebModel.SSOService.QueryUsersOrderBy OrderByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keyword {
            get {
                return this.KeywordField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordField, value) != true)) {
                    this.KeywordField = value;
                    this.RaisePropertyChanged("Keyword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InfrastructureService.WebModel.SSOService.QueryUsersOrderBy OrderBy {
            get {
                return this.OrderByField;
            }
            set {
                if ((this.OrderByField.Equals(value) != true)) {
                    this.OrderByField = value;
                    this.RaisePropertyChanged("OrderBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuerySignInLogsParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class QuerySignInLogsParameter : InfrastructureService.WebModel.SSOService.PagingParameter {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsUserNameExistsParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class IsUserNameExistsParameter : InfrastructureService.WebModel.SSOService.HeaderEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OAuthKind", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    public enum OAuthKind : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QQ = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weibo = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthEmailKind", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    public enum AuthEmailKind : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SignUp = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FindPassword = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChangeEmail = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthMobileKind", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    public enum AuthMobileKind : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SignUp = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FindPassword = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryUsersOrderBy", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    public enum QueryUsersOrderBy : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreateDateDesc = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreateDateAsc = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSOIdentity", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class SSOIdentity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAuthenticatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAuthenticated {
            get {
                return this.IsAuthenticatedField;
            }
            set {
                if ((this.IsAuthenticatedField.Equals(value) != true)) {
                    this.IsAuthenticatedField = value;
                    this.RaisePropertyChanged("IsAuthenticated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssueDate {
            get {
                return this.IssueDateField;
            }
            set {
                if ((this.IssueDateField.Equals(value) != true)) {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionID {
            get {
                return this.SessionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIDField, value) != true)) {
                    this.SessionIDField = value;
                    this.RaisePropertyChanged("SessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetIdentityParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class GetIdentityParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpiresDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpiresDate {
            get {
                return this.ExpiresDateField;
            }
            set {
                if ((this.ExpiresDateField.Equals(value) != true)) {
                    this.ExpiresDateField = value;
                    this.RaisePropertyChanged("ExpiresDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetServerConfigResult", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class GetServerConfigResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InfrastructureService.WebModel.SSOService.SSONotify[] NotifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TimeoutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InfrastructureService.WebModel.SSOService.SSONotify[] Notify {
            get {
                return this.NotifyField;
            }
            set {
                if ((object.ReferenceEquals(this.NotifyField, value) != true)) {
                    this.NotifyField = value;
                    this.RaisePropertyChanged("Notify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Timeout {
            get {
                return this.TimeoutField;
            }
            set {
                if ((this.TimeoutField.Equals(value) != true)) {
                    this.TimeoutField = value;
                    this.RaisePropertyChanged("Timeout");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSONotify", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class SSONotify : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientHandlerUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientHandlerUrl {
            get {
                return this.ClientHandlerUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientHandlerUrlField, value) != true)) {
                    this.ClientHandlerUrlField = value;
                    this.RaisePropertyChanged("ClientHandlerUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain {
            get {
                return this.DomainField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainField, value) != true)) {
                    this.DomainField = value;
                    this.RaisePropertyChanged("Domain");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerifyMobileParameter", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class VerifyMobileParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SmsCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SmsCode {
            get {
                return this.SmsCodeField;
            }
            set {
                if ((this.SmsCodeField.Equals(value) != true)) {
                    this.SmsCodeField = value;
                    this.RaisePropertyChanged("SmsCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecResultOfUserEntityrq7qyffr", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.PagedResultOfUserEntityrq7qyffr))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.QueryUsersResult))]
    public partial class ExecResultOfUserEntityrq7qyffr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InfrastructureService.WebModel.SSOService.UserEntity[] ResultSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InfrastructureService.WebModel.SSOService.UserEntity[] ResultSet {
            get {
                return this.ResultSetField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultSetField, value) != true)) {
                    this.ResultSetField = value;
                    this.RaisePropertyChanged("ResultSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedResultOfUserEntityrq7qyffr", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.QueryUsersResult))]
    public partial class PagedResultOfUserEntityrq7qyffr : InfrastructureService.WebModel.SSOService.ExecResultOfUserEntityrq7qyffr {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryUsersResult", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class QueryUsersResult : InfrastructureService.WebModel.SSOService.PagedResultOfUserEntityrq7qyffr {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserEntity", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class UserEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InfrastructureService.WebModel.SSOService.UserFlags FlagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InfrastructureService.WebModel.SSOService.UserFlags Flags {
            get {
                return this.FlagsField;
            }
            set {
                if ((this.FlagsField.Equals(value) != true)) {
                    this.FlagsField = value;
                    this.RaisePropertyChanged("Flags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFlags", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    public enum UserFlags : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticEmail = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticMobile = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecResultOfQuerySignInLogsResult.TResultrq7qyffr", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.PagedResultOfQuerySignInLogsResultTResultrq7qyffr))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.QuerySignInLogsResult))]
    public partial class ExecResultOfQuerySignInLogsResultTResultrq7qyffr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InfrastructureService.WebModel.SSOService.QuerySignInLogsResult.TResult[] ResultSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InfrastructureService.WebModel.SSOService.QuerySignInLogsResult.TResult[] ResultSet {
            get {
                return this.ResultSetField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultSetField, value) != true)) {
                    this.ResultSetField = value;
                    this.RaisePropertyChanged("ResultSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedResultOfQuerySignInLogsResult.TResultrq7qyffr", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InfrastructureService.WebModel.SSOService.QuerySignInLogsResult))]
    public partial class PagedResultOfQuerySignInLogsResultTResultrq7qyffr : InfrastructureService.WebModel.SSOService.ExecResultOfQuerySignInLogsResultTResultrq7qyffr {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordCount {
            get {
                return this.RecordCountField;
            }
            set {
                if ((this.RecordCountField.Equals(value) != true)) {
                    this.RecordCountField = value;
                    this.RaisePropertyChanged("RecordCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuerySignInLogsResult", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
    [System.SerializableAttribute()]
    public partial class QuerySignInLogsResult : InfrastructureService.WebModel.SSOService.PagedResultOfQuerySignInLogsResultTResultrq7qyffr {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SignInCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SignInCount {
            get {
                return this.SignInCountField;
            }
            set {
                if ((this.SignInCountField.Equals(value) != true)) {
                    this.SignInCountField = value;
                    this.RaisePropertyChanged("SignInCount");
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="QuerySignInLogsResult.TResult", Namespace="http://schemas.datacontract.org/2004/07/InfrastructureService.Model.User")]
        [System.SerializableAttribute()]
        public partial class TResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ClientIPField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private bool IsSuccessField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PlatformField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private System.DateTime SignInDateField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string UserNameField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ClientIP {
                get {
                    return this.ClientIPField;
                }
                set {
                    if ((object.ReferenceEquals(this.ClientIPField, value) != true)) {
                        this.ClientIPField = value;
                        this.RaisePropertyChanged("ClientIP");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool IsSuccess {
                get {
                    return this.IsSuccessField;
                }
                set {
                    if ((this.IsSuccessField.Equals(value) != true)) {
                        this.IsSuccessField = value;
                        this.RaisePropertyChanged("IsSuccess");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Platform {
                get {
                    return this.PlatformField;
                }
                set {
                    if ((object.ReferenceEquals(this.PlatformField, value) != true)) {
                        this.PlatformField = value;
                        this.RaisePropertyChanged("Platform");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.DateTime SignInDate {
                get {
                    return this.SignInDateField;
                }
                set {
                    if ((this.SignInDateField.Equals(value) != true)) {
                        this.SignInDateField = value;
                        this.RaisePropertyChanged("SignInDate");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string UserName {
                get {
                    return this.UserNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                        this.UserNameField = value;
                        this.RaisePropertyChanged("UserName");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SSOService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/IsUserNameExists", ReplyAction="http://tempuri.org/IUserService/IsUserNameExistsResponse")]
        bool IsUserNameExists(InfrastructureService.WebModel.SSOService.IsUserNameExistsParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SignUp", ReplyAction="http://tempuri.org/IUserService/SignUpResponse")]
        void SignUp(InfrastructureService.WebModel.SSOService.SignUpParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SignIn", ReplyAction="http://tempuri.org/IUserService/SignInResponse")]
        InfrastructureService.WebModel.SSOService.SSOIdentity SignIn(InfrastructureService.WebModel.SSOService.SignInParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/OAuth", ReplyAction="http://tempuri.org/IUserService/OAuthResponse")]
        InfrastructureService.WebModel.SSOService.SSOIdentity OAuth(InfrastructureService.WebModel.SSOService.OAuthParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetIdentity", ReplyAction="http://tempuri.org/IUserService/GetIdentityResponse")]
        InfrastructureService.WebModel.SSOService.SSOIdentity GetIdentity(InfrastructureService.WebModel.SSOService.GetIdentityParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SignOut", ReplyAction="http://tempuri.org/IUserService/SignOutResponse")]
        void SignOut(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetServerConfig", ReplyAction="http://tempuri.org/IUserService/GetServerConfigResponse")]
        InfrastructureService.WebModel.SSOService.GetServerConfigResult GetServerConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SendAuthEmail", ReplyAction="http://tempuri.org/IUserService/SendAuthEmailResponse")]
        void SendAuthEmail(InfrastructureService.WebModel.SSOService.SendAuthEmailParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/VerifyEmail", ReplyAction="http://tempuri.org/IUserService/VerifyEmailResponse")]
        void VerifyEmail(System.Guid authCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SendAuthMobile", ReplyAction="http://tempuri.org/IUserService/SendAuthMobileResponse")]
        void SendAuthMobile(InfrastructureService.WebModel.SSOService.SendAuthMobileParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/VerifyMobile", ReplyAction="http://tempuri.org/IUserService/VerifyMobileResponse")]
        void VerifyMobile(InfrastructureService.WebModel.SSOService.VerifyMobileParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SendFindPwdCode", ReplyAction="http://tempuri.org/IUserService/SendFindPwdCodeResponse")]
        void SendFindPwdCode(InfrastructureService.WebModel.SSOService.SendFindPwdCodeParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ChangePassword", ReplyAction="http://tempuri.org/IUserService/ChangePasswordResponse")]
        void ChangePassword(InfrastructureService.WebModel.SSOService.ChangePasswordParameter param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/QueryUsers", ReplyAction="http://tempuri.org/IUserService/QueryUsersResponse")]
        InfrastructureService.WebModel.SSOService.QueryUsersResult QueryUsers(InfrastructureService.WebModel.SSOService.QueryUsersParameter pager);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/QuerySignInLogs", ReplyAction="http://tempuri.org/IUserService/QuerySignInLogsResponse")]
        InfrastructureService.WebModel.SSOService.QuerySignInLogsResult QuerySignInLogs(InfrastructureService.WebModel.SSOService.QuerySignInLogsParameter pager);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : InfrastructureService.WebModel.SSOService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<InfrastructureService.WebModel.SSOService.IUserService>, InfrastructureService.WebModel.SSOService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsUserNameExists(InfrastructureService.WebModel.SSOService.IsUserNameExistsParameter param) {
            return base.Channel.IsUserNameExists(param);
        }
        
        public void SignUp(InfrastructureService.WebModel.SSOService.SignUpParameter param) {
            base.Channel.SignUp(param);
        }
        
        public InfrastructureService.WebModel.SSOService.SSOIdentity SignIn(InfrastructureService.WebModel.SSOService.SignInParameter param) {
            return base.Channel.SignIn(param);
        }
        
        public InfrastructureService.WebModel.SSOService.SSOIdentity OAuth(InfrastructureService.WebModel.SSOService.OAuthParameter param) {
            return base.Channel.OAuth(param);
        }
        
        public InfrastructureService.WebModel.SSOService.SSOIdentity GetIdentity(InfrastructureService.WebModel.SSOService.GetIdentityParameter param) {
            return base.Channel.GetIdentity(param);
        }
        
        public void SignOut(string token) {
            base.Channel.SignOut(token);
        }
        
        public InfrastructureService.WebModel.SSOService.GetServerConfigResult GetServerConfig() {
            return base.Channel.GetServerConfig();
        }
        
        public void SendAuthEmail(InfrastructureService.WebModel.SSOService.SendAuthEmailParameter param) {
            base.Channel.SendAuthEmail(param);
        }
        
        public void VerifyEmail(System.Guid authCode) {
            base.Channel.VerifyEmail(authCode);
        }
        
        public void SendAuthMobile(InfrastructureService.WebModel.SSOService.SendAuthMobileParameter param) {
            base.Channel.SendAuthMobile(param);
        }
        
        public void VerifyMobile(InfrastructureService.WebModel.SSOService.VerifyMobileParameter param) {
            base.Channel.VerifyMobile(param);
        }
        
        public void SendFindPwdCode(InfrastructureService.WebModel.SSOService.SendFindPwdCodeParameter param) {
            base.Channel.SendFindPwdCode(param);
        }
        
        public void ChangePassword(InfrastructureService.WebModel.SSOService.ChangePasswordParameter param) {
            base.Channel.ChangePassword(param);
        }
        
        public InfrastructureService.WebModel.SSOService.QueryUsersResult QueryUsers(InfrastructureService.WebModel.SSOService.QueryUsersParameter pager) {
            return base.Channel.QueryUsers(pager);
        }
        
        public InfrastructureService.WebModel.SSOService.QuerySignInLogsResult QuerySignInLogs(InfrastructureService.WebModel.SSOService.QuerySignInLogsParameter pager) {
            return base.Channel.QuerySignInLogs(pager);
        }
    }
}
